language: objective-c
osx_image: xcode7.3

script:
- set -o pipefail && xcodebuild test -workspace Example/ASPlaceholderTextView.xcworkspace -scheme ASPlaceholderTextView-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
